# Generated by Django 5.1.3 on 2024-12-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0003_alter_movie_count_of_view_alter_movie_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_slider', models.ImageField(upload_to='poster_slider/')),
                ('show', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='movie.movie')),
            ],
        ),
    ]
