# Generated by Django 5.1.3 on 2024-12-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_created_at_review_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='count_of_view',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
