# Generated by Django 5.1.3 on 2024-12-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_count_of_view_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(upload_to='trailer_movie/'),
        ),
    ]
