# Generated by Django 5.1.3 on 2024-12-03 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0003_alter_movie_count_of_view_alter_movie_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_actor/')),
                ('wikipedia_url', models.URLField()),
                ('role_level', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Intermediate'), (3, 'Low')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ManyToManyField(related_name='actors', to='movie.movie')),
            ],
        ),
    ]
