# Generated by Django 5.1.3 on 2024-12-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='role_level',
        ),
    ]
