# Generated by Django 5.1.3 on 2024-12-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_remove_actor_role_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(upload_to='photo_actor/'),
        ),
    ]
